"""
scripts/migrate_pages.py
Auto-migrate semua file di pages/ jadi anonim (Pustaka Struk).

FITUR:
- --dry-run  : Preview tanpa edit (WAJIB coba dulu)
- --check    : Cek status migrasi
- --backup   : Backup pages/ ke pages_backup/
- --rollback : Restore dari backup
- (default)  : Migrate beneran

CARA PAKAI (dari root repo):
    python scripts/migrate_pages.py --dry-run
    python scripts/migrate_pages.py
    python scripts/migrate_pages.py --rollback
"""

import os
import sys
import re
import shutil
import argparse
from pathlib import Path
from datetime import datetime


# ============================================================
# KONFIGURASI
# ============================================================
PAGES_DIR = "pages"
BACKUP_DIR = "pages_backup"
LOG_FILE = "migrate_log.txt"

MARKER_MIGRATED = "setup_anonim_page"

IMPORT_LINE = (
    "from utils.anonim import "
    "setup_anonim_page, render_nav_buttons, render_header"
)

NAV_FOOTER = (
    "\n\n# === Navigasi custom (auto-generated by migrate_pages.py) ===\n"
    "render_nav_buttons()\n"
)


# ============================================================
# UTILS
# ============================================================
def log(msg, file_log=None, also_print=True):
    """Print + tulis ke log file."""
    if also_print:
        print(msg)
    if file_log:
        with open(file_log, "a", encoding="utf-8") as f:
            f.write(f"{msg}\n")


def get_page_title(filename):
    """'1_PSM_per_PLU.py' -> 'PSM per PLU'"""
    name = Path(filename).stem
    name = re.sub(r"^\d+_", "", name)
    name = name.replace("_", " ")
    return name


def is_already_migrated(content):
    """Cek apakah file udah pernah di-migrate."""
    return MARKER_MIGRATED in content


def find_set_page_config(content):
    """
    Cari blok st.set_page_config(...) lengkap.
    Return (start, end) atau None.
    """
    match = re.search(r"st\.set_page_config\s*\(", content)
    if not match:
        return None

    start = match.start()
    depth = 0
    i = match.start()
    in_string = None
    while i < len(content):
        ch = content[i]
        # Handle string
        if in_string:
            if ch == in_string and content[i-1] != "\\":
                in_string = None
        elif ch in ('"', "'"):
            in_string = ch
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return (start, i + 1)
        i += 1
    return None


def find_last_import_index(content):
    """Cari index baris terakhir yang masih import."""
    lines = content.split("\n")
    last = -1
    for i, line in enumerate(lines):
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        if s.startswith("import ") or s.startswith("from "):
            last = i
        elif last >= 0:
            break
    return last + 1


# ============================================================
# MIGRATE LOGIC
# ============================================================
def migrate_content(content, filename):
    """
    Migrate content. Return (new_content, list_of_changes).
    """
    title = get_page_title(filename)
    changes = []

    # === 1. Tambah import ===
    if IMPORT_LINE not in content:
        idx = find_last_import_index(content)
        lines = content.split("\n")
        lines.insert(idx, IMPORT_LINE)
        content = "\n".join(lines)
        changes.append("import_added")

    # === 2. Ganti / tambah setup_anonim_page ===
    config_match = find_set_page_config(content)
    new_setup = f'setup_anonim_page("{title}", "📊")'
    if config_match:
        s, e = config_match
        content = content[:s] + new_setup + content[e:]
        changes.append("config_replaced")
    else:
        idx = find_last_import_index(content)
        lines = content.split("\n")
        # Insert setelah import
        lines.insert(idx, "")
        lines.insert(idx + 1, new_setup)
        content = "\n".join(lines)
        changes.append("config_added")

    # === 3. Tambah render_nav_buttons di bawah ===
    if "render_nav_buttons()" not in content:
        content = content.rstrip() + NAV_FOOTER
        changes.append("nav_added")

    return content, changes


# ============================================================
# ACTIONS
# ============================================================
def scan_pages():
    pages_path = Path(PAGES_DIR)
    if not pages_path.exists():
        print(f"❌ Folder '{PAGES_DIR}/' tidak ditemukan.")
        print(f"   Pastikan kamu jalanin script dari root repo.")
        sys.exit(1)

    files = sorted(pages_path.glob("*.py"))
    # Skip file yang diawali underscore (__init__.py, dll)
    files = [f for f in files if not f.name.startswith("_")]
    return files


def do_dry_run(files):
    print("\n🔍 DRY RUN MODE — Tidak ada file yang diubah\n")
    print(f"📁 Scanning {PAGES_DIR}/ ...")
    print(f"   Found {len(files)} file\n")

    stats = {"will_migrate": 0, "already": 0, "error": 0}

    for f in files:
        print(f"📄 File: {f}")

        try:
            content = f.read_text(encoding="utf-8")
        except Exception as e:
            print(f"   ❌ Error baca: {e}\n")
            stats["error"] += 1
            continue

        if is_already_migrated(content):
            print(f"   ⏭️  Sudah di-migrate — skip\n")
            stats["already"] += 1
            continue

        _, changes = migrate_content(content, f.name)

        print(f"   ✅ Belum di-migrate")
        if "import_added" in changes:
            print(f"   → Tambah: import")
        if "config_replaced" in changes:
            print(f"   → Ganti: st.set_page_config → setup_anonim_page()")
        if "config_added" in changes:
            print(f"   → Tambah: setup_anonim_page()")
        if "nav_added" in changes:
            print(f"   → Tambah: render_nav_buttons()")
        print()
        stats["will_migrate"] += 1

    print("📊 RINGKASAN:")
    print(f"   Total file       : {len(files)}")
    print(f"   Akan di-migrate  : {stats['will_migrate']}")
    print(f"   Sudah di-migrate : {stats['already']}")
    print(f"   Error            : {stats['error']}")
    print()
    print("⚠️  Jalankan tanpa --dry-run untuk eksekusi.\n")


def do_backup():
    pages_path = Path(PAGES_DIR)
    backup_path = Path(BACKUP_DIR)

    if not pages_path.exists():
        print(f"❌ Folder '{PAGES_DIR}/' tidak ditemukan.")
        sys.exit(1)

    if backup_path.exists():
        print(f"🗑️  Hapus backup lama: {BACKUP_DIR}/")
        shutil.rmtree(backup_path)

    shutil.copytree(pages_path, backup_path)
    print(f"💾 Backup dibuat: {BACKUP_DIR}/")
    print(f"   {len(list(backup_path.glob('*.py')))} file di-backup\n")


def do_migrate(files):
    print("\n🚀 MIGRATE MODE — File akan diubah\n")

    # Auto-backup
    do_backup()

    file_log = LOG_FILE
    with open(file_log, "w", encoding="utf-8") as f:
        f.write(f"=== MIGRATE LOG ===\n")
        f.write(f"Tanggal: {datetime.now().isoformat()}\n\n")

    stats = {"migrated": 0, "skipped": 0, "error": 0}

    for f in files:
        log(f"📄 Processing: {f}", file_log)

        try:
            content = f.read_text(encoding="utf-8")
        except Exception as e:
            log(f"   ❌ Error baca: {e}\n", file_log)
            stats["error"] += 1
            continue

        if is_already_migrated(content):
            log(f"   ⏭️  Sudah di-migrate — skip\n", file_log)
            stats["skipped"] += 1
            continue

        try:
            new_content, changes = migrate_content(content, f.name)
            f.write_text(new_content, encoding="utf-8")

            log(f"   ✅ Berhasil di-migrate", file_log)
            for c in changes:
                log(f"      • {c}", file_log)
            log("", file_log)
            stats["migrated"] += 1

        except Exception as e:
            log(f"   ❌ Error migrate: {e}\n", file_log)
            stats["error"] += 1

    log("📊 RINGKASAN:", file_log)
    log(f"   ✅ Migrated : {stats['migrated']} file", file_log)
    log(f"   ⏭️  Skipped  : {stats['skipped']} file", file_log)
    log(f"   ❌ Error    : {stats['error']} file", file_log)
    log(f"\n📝 Log tersimpan: {LOG_FILE}", file_log)
    log(f"💾 Backup: {BACKUP_DIR}/", file_log)
    log(f"\n💡 Rollback kalau ada masalah:", file_log)
    log(f"   python scripts/migrate_pages.py --rollback", file_log)
    print()


def do_rollback():
    pages_path = Path(PAGES_DIR)
    backup_path = Path(BACKUP_DIR)

    if not backup_path.exists():
        print(f"❌ Backup '{BACKUP_DIR}/' tidak ditemukan.")
        print(f"   Gak bisa rollback.")
        sys.exit(1)

    print(f"⚠️  Ini akan menghapus {PAGES_DIR}/ dan restore dari {BACKUP_DIR}/")
    try:
        confirm = input("Lanjutkan? (y/N): ").strip().lower()
    except EOFError:
        confirm = "n"

    if confirm != "y":
        print("❌ Rollback dibatalkan.")
        return

    if pages_path.exists():
        shutil.rmtree(pages_path)

    shutil.copytree(backup_path, pages_path)
    print(f"✅ Rollback berhasil!")
    print(f"   {len(list(pages_path.glob('*.py')))} file di-restore dari backup")


def do_check(files):
    print("\n🔍 CHECK STATUS\n")
    print(f"📁 {PAGES_DIR}/ — {len(files)} file\n")

    migrated = []
    not_migrated = []

    for f in files:
        try:
            content = f.read_text(encoding="utf-8")
            if is_already_migrated(content):
                migrated.append(f.name)
            else:
                not_migrated.append(f.name)
        except Exception as e:
            print(f"❌ Error baca {f}: {e}")

    print(f"✅ Sudah di-migrate ({len(migrated)}):")
    for name in migrated:
        print(f"   • {name}")
    print()

    print(f"⬜ Belum di-migrate ({len(not_migrated)}):")
    for name in not_migrated:
        print(f"   • {name}")
    print()

    backup_path = Path(BACKUP_DIR)
    if backup_path.exists():
        print(f"💾 Backup ada: {BACKUP_DIR}/")
    else:
        print(f"⚠️  Belum ada backup. Script migrate akan bikin otomatis.")


# ============================================================
# MAIN
# ============================================================
def main():
    parser = argparse.ArgumentParser(
        description="Auto-migrate halaman Streamlit jadi anonim",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Contoh:
  python scripts/migrate_pages.py --dry-run
  python scripts/migrate_pages.py --check
  python scripts/migrate_pages.py --backup
  python scripts/migrate_pages.py
  python scripts/migrate_pages.py --rollback
        """
    )
    parser.add_argument("--dry-run", action="store_true",
                        help="Preview tanpa edit")
    parser.add_argument("--backup", action="store_true",
                        help="Backup pages/ doang")
    parser.add_argument("--rollback", action="store_true",
                        help="Restore dari backup")
    parser.add_argument("--check", action="store_true",
                        help="Cek status migrasi")

    args = parser.parse_args()

    print("=" * 60)
    print("🚀 migrate_pages.py — Auto Migrate Halaman ke Anonim")
    print("=" * 60)

    if args.rollback:
        do_rollback()
        return

    files = scan_pages()

    if args.check:
        do_check(files)
        return

    if args.backup:
        do_backup()
        print("💡 Sekarang jalankan tanpa --backup untuk migrate.")
        return

    if args.dry_run:
        do_dry_run(files)
        return

    print(f"\n📁 Scanning {PAGES_DIR}/ ...")
    print(f"   Found {len(files)} file")
    do_migrate(files)


if __name__ == "__main__":
    main()
